### ISSUE TITLE
gas concentration (ppm)

### ISSUE THREAD

**Issue by mshaposhnikov** [FlyingDiver/Indigo-Masquerade#2]
Could you please add gas concentration (ppm)? Using MQ to create Netatmo virtual devices

I.e. it should be 595ppm

![Screenshot 2019-06-03 at 13 26 22](https://user-images.githubusercontent.com/37839531/58802042-0e55b580-8604-11e9-809b-1b6b2ae6798f.png)

**Comment by FlyingDiver** [comment]
Pre-release 0.1.6.
