### ISSUE TITLE
Error in plugin execution ServerReplacedElem

### ISSUE THREAD

**Issue by johnsturgeon** [FlyingDiver/Indigo-Masquerade#3]
Yep, me again.

I just installed the plugin Masquerade, and added a new device
<img width="592" alt="image" src="https://user-images.githubusercontent.com/9746310/98572700-c4e2ae80-226a-11eb-8c9f-89f6839d2128.png">
And got the following error:

```
   Masquerade Error                Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "plugin.py", line 182, in deviceUpdated
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1179, in deviceUpdated
  File "plugin.py", line 77, in deviceStartComm
  File "plugin.py", line 228, in updateDevice
ValueError: could not convert string to float: quick
```

**Comment by FlyingDiver** [comment]
What exactly were you trying to do?  Mode is a non-numeric state, you can't convert that to a sensor device.

**Comment by johnsturgeon** [comment]
I'm trying to create a virtual device that can show me the current state of the air cleaner mode for my Nexia Trane Thermostat

**Comment by FlyingDiver** [comment]
Show where?  Indigo UI?  Or a control page?  You should be able to put that state directly on the control page.

**Comment by johnsturgeon** [comment]
Indigo UI, I don't use control pages.  I suppose I could write a schedule that queries the value and sets a variable every `n` minutes...

**Comment by FlyingDiver** [comment]
You don't need a schedule, just create a trigger that updates the variable any time the state changes.  But yeah, you'll need to use a variable.  Masquerade is designed to do behavior more than UI.
