### ISSUE TITLE
sprinkler zone

### ISSUE THREAD

**Issue by icygame** [FlyingDiver/Indigo-Masquerade#4]
Would be very handy to be able to masquerade an on/off device as a sprinkler zone. 

Indigo already provides the ability to create a virtual sprinkler device  grouping zones from disparate controllers, but they need to be native sprinkler devices. The native sprinkler device provides access to a range of useful functions relating to UI, scheduling, sequential firing, and running pumps - functionality that is not accessible to conventional relay devices.

A couple of use cases:

1. A sprinkler group is defined but an associated pump is operated by a z-wave relay. Mascquerading the pump relay as a sprinkler zone would enable use of the native indigo UI.
2. Rather than use an irrigation controller for an isolated zone, I use a 24 volt transformer directly switched by a zwave relay. Mascquerading the relay as a sprinkler zone would enable the zone to be grouped with other native sprinkler zones.

Presumably, the parent on/off device would still be functional.

**Comment by FlyingDiver** [comment]
0.2.0
