### ISSUE TITLE
Add elapsed time as a sensor type?

### ISSUE THREAD

**Issue by cronutan** [FlyingDiver/Indigo-Masquerade#7]
Would it be possible to add elapsed time as one of the sensor types?
I have several devices that report elapsed time in seconds, but I would like to display something more readable like 1 day, 2 hours, 12 min

On plugin that I use that gives me seconds is MiniUniFi and I use the uptime and offline_seconds but that is not something I can show the user.

Currently I use a trigger and populate variables, but that is a bit cumbersome as I need to have one trigger per value.  

I use the following to convert seconds to display text: 
```
intervals = (
    ('weeks', 604800),  # 60 * 60 * 24 * 7
    ('days', 86400),    # 60 * 60 * 24
    ('hours', 3600),    # 60 * 60
    ('min', 60),
#    ('sec', 1),
    )

def display_time(seconds, granularity=4):
    result = []

    for name, count in intervals:
        value = seconds // count
        if value:
            seconds -= value * count
            if value == 1:
                name = name.rstrip('s')
            result.append("{} {}".format(value, name))
    return ', '.join(result[:granularity])

**Comment by FlyingDiver** [comment]
That's really outside the scope of the plugin.  Try https://github.com/Colorado4Wheeler/Device-Extensions/wiki/Conversion-Devices#convert-between-date-formats

**Comment by cronutan** [comment]
Looks like something that would work perfectly here.  Thank you.
